# Generated by Django 5.1.1 on 2025-10-06 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prisederef', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE prisederef_reference ALTER COLUMN interview_date DROP NOT NULL;",
            reverse_sql="ALTER TABLE prisederef_reference ALTER COLUMN interview_date SET NOT NULL;"
        ),
    ]
