# Generated by Django 5.1.1 on 2025-10-06 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prisederef', '0002_auto_20251006_0603'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE prisederef_reference ALTER COLUMN recruiter_id DROP NOT NULL;",
            reverse_sql="ALTER TABLE prisederef_reference ALTER COLUMN recruiter_id SET NOT NULL;"
        ),
    ]
