# Generated by Django 5.1.1 on 2025-10-06 06:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prisederef', '0003_auto_20251006_0606'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
