# Generated by Django 5.1.1 on 2025-10-06 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prisederef', '0004_recruiter_created_at_recruiter_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='recruiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='references', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Recruiter',
        ),
    ]
