# Generated by Django 5.1.1 on 2025-10-06 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prisederef', '0005_alter_reference_recruiter_delete_recruiter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('email', 'Email'), ('phone', 'Téléphone'), ('meeting', 'Réunion'), ('other', 'Autre')], max_length=20)),
                ('interaction_date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True)),
                ('feedback', models.CharField(blank=True, choices=[('positive', 'Positif'), ('neutral', 'Neutre'), ('negative', 'Négatif')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_interactions', to=settings.AUTH_USER_MODEL)),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='prisederef.reference')),
            ],
            options={
                'ordering': ['-interaction_date'],
            },
        ),
    ]
