services:
  web:
    build: .
    command: /bin/sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    develop:
      watch:
        - action: rebuild
          path: .
          ignore:
            - .git/
            - node_modules/
            - __pycache__/
            - "*.pyc"

  worker:
    build: .
    user: "1000:1000"
    command: celery -A core worker -l info
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    develop:
      watch:
        - action: rebuild
          path: .
          ignore:
            - .git/
            - node_modules/
            - __pycache__/
            - "*.pyc"

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  pgdata:
